### ISSUE TITLE
There is no code here!

### ISSUE THREAD

**Issue by 7yl4r** [USF-IMARS/erddap_roi_to_timeseries#1]
I don't know where I was going with this 8 mo ago. I guess @dotis is the only one I know who has code to do this.
Dan: do you have code to share that pulls the ERDDAP data and makes a timeseries we could publish here?

**Comment by dotis** [comment]
I don't have any code for this, unfortunately. The code I use to generate time series is in MATLAB and extracts data from NC files directly and then saves as csv.
________________________________

**Comment by 7yl4r** [comment]
Ok. I'm going to delete this repo then. Thanks!
